# Generated by Django 4.2.5 on 2023-11-17 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_delete_sample'),
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantreplier',
            old_name='input_text',
            new_name='chatting_content',
        ),
        migrations.RemoveField(
            model_name='plantreplier',
            name='output_text',
        ),
        migrations.AddField(
            model_name='plantreplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantreplier',
            name='is_user_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantreplier',
            name='plant_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantreplier',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
