# Generated by Django 4.2.5 on 2023-10-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_rename_chatgpt_output_plantreplier__input_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantreplier',
            old_name='_input',
            new_name='input_text',
        ),
        migrations.RenameField(
            model_name='plantreplier',
            old_name='_output',
            new_name='output_text',
        ),
    ]
