# Generated by Django 4.2.5 on 2023-10-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='questioner_id',
            new_name='user',
        ),
    ]
