# Generated by Django 4.2.5 on 2023-11-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_community_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.question'),
        ),
    ]
