# Generated by Django 4.2.5 on 2023-10-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_question_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='question_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
