# Generated by Django 4.2.5 on 2023-11-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='question_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='community',
            name='answer_or_not',
        ),
        migrations.RemoveField(
            model_name='community',
            name='question_updated_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.community'),
        ),
    ]
