# Generated by Django 4.2.5 on 2023-10-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='test_address', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cultivation_experience',
            field=models.CharField(default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='garden_size',
            field=models.CharField(default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tiiun_number',
            field=models.CharField(default='test_tiiun_number', max_length=30),
            preserve_default=False,
        ),
    ]
