# Generated by Django 4.2.5 on 2023-10-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_cultivation_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cultivation_experience',
        ),
    ]
