# Generated by Django 4.2.5 on 2023-11-07 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_nickname', models.CharField(max_length=255)),
                ('plant_picture_url', models.CharField(max_length=255)),
                ('planted_at', models.DateTimeField()),
                ('harvested_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant_Disease_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_disease_name', models.CharField(max_length=100)),
                ('plant_disease_symptom', models.CharField(max_length=255)),
                ('plant_disease_condition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plant_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=30)),
                ('plant_temperature', models.CharField(max_length=30)),
                ('plant_humidity', models.CharField(max_length=30)),
                ('plant_illuminance', models.CharField(max_length=30)),
                ('plant_bloom_season', models.CharField(max_length=30)),
                ('plant_watering_cycle', models.CharField(max_length=30)),
                ('plant_difficulty', models.CharField(max_length=10)),
                ('plant_caution', models.CharField(max_length=255)),
                ('germination_period_start', models.IntegerField()),
                ('germination_period_end', models.IntegerField()),
                ('growth_period_start', models.IntegerField()),
                ('growth_period_end', models.IntegerField()),
                ('harvest_period_start', models.IntegerField()),
                ('harvest_period_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant_Disease_Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnose_photo_url', models.CharField(max_length=255)),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant_disease_type')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant_type'),
        ),
        migrations.AddField(
            model_name='plant',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
