# Generated by Django 4.2.5 on 2023-11-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='harvested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
