# Generated by Django 4.2.5 on 2023-11-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_harvested_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnose_photo_url', models.CharField(max_length=255)),
            ],
        ),
    ]
