# Generated by Django 4.2.5 on 2023-11-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_plant_disease_record_disease_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
